import type { Resource } from "./resources.types";

export const mockResources: Resource[] = [
  {
    id: "r-mdn-html",
    title: "HTML basics",
    provider: "MDN Web Docs",
    kind: "documentation",
    url: "https://developer.mozilla.org/en-US/docs/Learn_web_development/Core/Structuring_content",
    costLabel: "Course: free",
  },
  {
    id: "r-fcc-web",
    title: "Responsive Web Design",
    provider: "freeCodeCamp",
    kind: "interactive",
    url: "https://www.freecodecamp.org/learn/2022/responsive-web-design/",
    costLabel: "Course: free",
    certificationLabel: "Certification: free",
  },
  {
    id: "r-a11y-video",
    title: "Accessibility fundamentals",
    provider: "W3C Web Accessibility Initiative",
    kind: "video",
    url: "https://www.w3.org/WAI/videos/standards-and-benefits/",
    costLabel: "Course: cost unknown",
  },
  {
    id: "r-css-course",
    title: "Learn CSS",
    provider: "web.dev",
    kind: "course",
    url: "https://web.dev/learn/css",
    costLabel: "Course: paid",
  },
  {
    id: "r-grid-game",
    title: "Grid Garden",
    provider: "Codepip",
    kind: "interactive",
    url: "https://cssgridgarden.com/",
  },
  {
    id: "r-js-info",
    title: "JavaScript Guide",
    provider: "MDN Web Docs",
    kind: "documentation",
    url: "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide",
    costLabel: "Course: free",
  },
  {
    id: "r-meta-cert",
    title: "Introduction to Front-End Development",
    provider: "Meta",
    kind: "course",
    url: "https://www.coursera.org/learn/introduction-to-front-end-development",
    costLabel: "Course: free",
    certificationLabel: "Certification: paid · $49/month",
  },
  {
    id: "r-react-docs",
    title: "React Learn",
    provider: "React",
    kind: "documentation",
    url: "https://react.dev/learn",
    costLabel: "Course: free",
  },
];
