/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProtectedRouteImport } from './routes/_protected'
import { Route as authLoginRouteImport } from './routes/(auth)/login'
import { Route as ProtectedProgressRouteImport } from './routes/_protected/progress'
import { Route as CareersIndexRouteImport } from './routes/careers/index'
import { Route as CareersOnboardingIndexRouteImport } from './routes/careers/onboarding/index'
import { Route as CareersOnboardingAboutRouteImport } from './routes/careers/onboarding/about'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedRoute = ProtectedRouteImport.update({
  id: '/_protected',
  getParentRoute: () => rootRouteImport,
} as any)
const authLoginRoute = authLoginRouteImport.update({
  id: '/(auth)/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedProgressRoute = ProtectedProgressRouteImport.update({
  id: '/progress',
  path: '/progress',
  getParentRoute: () => ProtectedRoute,
} as any)
const CareersIndexRoute = CareersIndexRouteImport.update({
  id: '/careers/',
  path: '/careers/',
  getParentRoute: () => rootRouteImport,
} as any)
const CareersOnboardingIndexRoute = CareersOnboardingIndexRouteImport.update({
  id: '/careers/onboarding/',
  path: '/careers/onboarding/',
  getParentRoute: () => rootRouteImport,
} as any)
const CareersOnboardingAboutRoute = CareersOnboardingAboutRouteImport.update({
  id: '/careers/onboarding/about',
  path: '/careers/onboarding/about',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof authLoginRoute
  '/progress': typeof ProtectedProgressRoute
  '/careers/': typeof CareersIndexRoute
  '/careers/onboarding/about': typeof CareersOnboardingAboutRoute
  '/careers/onboarding/': typeof CareersOnboardingIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof authLoginRoute
  '/progress': typeof ProtectedProgressRoute
  '/careers': typeof CareersIndexRoute
  '/careers/onboarding/about': typeof CareersOnboardingAboutRoute
  '/careers/onboarding': typeof CareersOnboardingIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_protected': typeof ProtectedRouteWithChildren
  '/(auth)/login': typeof authLoginRoute
  '/_protected/progress': typeof ProtectedProgressRoute
  '/careers/': typeof CareersIndexRoute
  '/careers/onboarding/about': typeof CareersOnboardingAboutRoute
  '/careers/onboarding/': typeof CareersOnboardingIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/progress'
    | '/careers/'
    | '/careers/onboarding/about'
    | '/careers/onboarding/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/progress'
    | '/careers'
    | '/careers/onboarding/about'
    | '/careers/onboarding'
  id:
    | '__root__'
    | '/'
    | '/_protected'
    | '/(auth)/login'
    | '/_protected/progress'
    | '/careers/'
    | '/careers/onboarding/about'
    | '/careers/onboarding/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ProtectedRoute: typeof ProtectedRouteWithChildren
  authLoginRoute: typeof authLoginRoute
  CareersIndexRoute: typeof CareersIndexRoute
  CareersOnboardingAboutRoute: typeof CareersOnboardingAboutRoute
  CareersOnboardingIndexRoute: typeof CareersOnboardingIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected': {
      id: '/_protected'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ProtectedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/login': {
      id: '/(auth)/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof authLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected/progress': {
      id: '/_protected/progress'
      path: '/progress'
      fullPath: '/progress'
      preLoaderRoute: typeof ProtectedProgressRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/careers/': {
      id: '/careers/'
      path: '/careers'
      fullPath: '/careers/'
      preLoaderRoute: typeof CareersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/careers/onboarding/': {
      id: '/careers/onboarding/'
      path: '/careers/onboarding'
      fullPath: '/careers/onboarding/'
      preLoaderRoute: typeof CareersOnboardingIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/careers/onboarding/about': {
      id: '/careers/onboarding/about'
      path: '/careers/onboarding/about'
      fullPath: '/careers/onboarding/about'
      preLoaderRoute: typeof CareersOnboardingAboutRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface ProtectedRouteChildren {
  ProtectedProgressRoute: typeof ProtectedProgressRoute
}

const ProtectedRouteChildren: ProtectedRouteChildren = {
  ProtectedProgressRoute: ProtectedProgressRoute,
}

const ProtectedRouteWithChildren = ProtectedRoute._addFileChildren(
  ProtectedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ProtectedRoute: ProtectedRouteWithChildren,
  authLoginRoute: authLoginRoute,
  CareersIndexRoute: CareersIndexRoute,
  CareersOnboardingAboutRoute: CareersOnboardingAboutRoute,
  CareersOnboardingIndexRoute: CareersOnboardingIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
